kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-order-app-deployment
  namespace: nginx       # order-app
  labels:
    app: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: souvik741156/order-api
        ports:
        - containerPort: 3000
