apiVersion: v1
kind: Service
metadata:
  name: order-app-service
  namespace: nginx       # order-app
spec:
  selector:
    app: order-app
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Pod port
  type: ClusterIP
